### PR TITLE
Refactor Duplicate Code and use the tdk-py library

### PR DESCRIPTION
**Pull request by emreozcan**
Use Extract Method[^1] to unify creating message
texts for both the Telegram and Discord bots.
Both platforms can use the same text since they
both support Markdown for formatting.

The other change is to use the tdk-py library.
This avoids trying to manually parse objects
returned from TDK, so it's less error prone now.
Also, we get better editor auto-completion now :^)

[^1]: See https://refactoring.guru/extract-method

### CODE REVIEW

**Comment by berkantkz** [comment]
Brilliant! Merging the pull request now even though I am unable to test it personally and think that it is tested by you already.

**Comment by berkantkz** [comment]
Just tested and 
```console
        *** DISCORD BOT ***
Message from berkantkz#7475: <@966110075901083648> anlam
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\berka\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\berka\stuff\tdksozlukbot\tdksozlukbot.py", line 125, in on_message
    metin = prepare_text_from_word(arama_sonuclari[0])
NameError: name 'prepare_text_from_word' is not defined
```

**Comment by emreozcan** [comment]
Aaah, I didn't know `discord.Client.run()` was blocking. I guess everybody makes simle misktakes, huh 😅.

Moving the lines 134-135 to the end of the file should fix the error.

**Comment by berkantkz** [comment]
> Just tested and
> 
> ```
>         *** DISCORD BOT ***
> Message from berkantkz#7475: <@966110075901083648> anlam
> Ignoring exception in on_message
> Traceback (most recent call last):
>   File "C:\Users\berka\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "C:\Users\berka\stuff\tdksozlukbot\tdksozlukbot.py", line 125, in on_message
>     metin = prepare_text_from_word(arama_sonuclari[0])
> NameError: name 'prepare_text_from_word' is not defined
> ```

obviously moving the "prepare_text_from_word(word: tdk.models.Entry) function to very top of the code, right below import statements, solves the issue ~~-but: telegram login does not work unlike it did before merging the commit~~.

**Comment by emreozcan** [comment]
That's interesting, the bot code or the code about environment variables weren't modified.

**Comment by berkantkz** [comment]
Hold on.

This was my bad (about the telegram login). I put the wrong token for it.

**Comment by emreozcan** [comment]
Oh, okay. Sorry about the NameError.

**Comment by berkantkz** [comment]
It's fine! That was a good job.

**Pull request merged**
